name: deepRTS
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libcxx=19.1.7
  - libffi=3.4.4
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.3
  - python=3.9.23
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - cloudpickle==3.1.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.19.1
      - fonttools==4.60.2
      - fsspec==2025.10.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - gymnasium==1.0.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jpype1==1.6.0
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.3
      - peewee==3.19.0
      - pettingzoo==1.25.0
      - pillow==11.3.0
      - pygame==2.6.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rich==14.2.0
      - six==1.17.0
      - stable-baselines3[extra]==2.4.1
      - sb3-contrib==2.4.0
      - sympy==1.14.0
      - torch==2.2.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - zipp==3.23.0
prefix: /Users/fcp/opt/anaconda3/envs/deepRTS
